### ISSUE TITLE
Delete Item Bookmarklet

### ISSUE THREAD

**Issue by Jacoby-Powell** [CloudWaddie/infinite-craft-hack#1]
**UNINTENTIONAL POST- WRONG ACCOUNT**

**Comment by Jacoby-Powell** [comment]
javascript:(function()%7B(function()%20%7Blet%20doesExists%20%3D%20localStorage.getItem(%22infinite-craft-data%22)%3Blet%20confirmed%3Bif%20(doesExists%20%3D%3D%20null)%20%7Balert(%22No%20items%20exist%20in%20the%20local%20storage.%22)%3Breturn%3B%7Dlet%20initial%20%3D%20localStorage.getItem(%22infinite-craft-data%22)%3Blet%20array%20%3D%20JSON.parse(initial).elements%3Blet%20text%20%3D%20prompt(%22What%20is%20the%20name%20of%20the%20item%20to%20delete%3F%22)%3Blet%20itemIndex%20%3D%20array.findIndex(item%20%3D%3E%20item.text%20%3D%3D%3D%20text)%3Bif%20(itemIndex%20%3D%3D%3D%20-1)%20%7Balert(%22Item%20not%20found%20in%20the%20local%20storage.%22)%3Breturn%3B%7Dconfirmed%20%3D%20confirm(%22Are%20you%20sure%20you%20want%20to%20delete%20this%20item%3F%20This%20CANNOT%20be%20easily%20undone!%22)%3Bif%20(confirmed%20%3D%3D%20true)%20%7Barray.splice(itemIndex%2C%201)%3Blet%20newItem%20%3D%20%7Belements%3A%20array%7D%3Barray%20%3D%20JSON.stringify(newItem)%3BlocalStorage.setItem(%22infinite-craft-data%22%2C%20array)%3Balert(%22Item%20deleted!%20Reloading!%22)%3Bwindow.location.reload()%3B%7Dconsole.log(%22DONE%22)%3B%7D)()%7D)()

**Comment by NerdyDragon777** [comment]
javascript:(function()%7B(function()%20%7Blet%20doesExists%20%3D%20localStorage.getItem(%22infinite-craft-data%22)%3Blet%20confirmed%3Bif%20(doesExists%20%3D%3D%20null)%20%7Balert(%22No%20items%20exist%20in%20the%20local%20storage.%22)%3Breturn%3B%7Dlet%20initial%20%3D%20localStorage.getItem(%22infinite-craft-data%22)%3Blet%20array%20%3D%20JSON.parse(initial).elements%3Blet%20text%20%3D%20prompt(%22What%20is%20the%20name%20of%20the%20item%20to%20delete%3F%22)%3Blet%20itemIndex%20%3D%20array.findIndex(item%20%3D%3E%20item.text%20%3D%3D%3D%20text)%3Bif%20(itemIndex%20%3D%3D%3D%20-1)%20%7Balert(%22Item%20not%20found%20in%20the%20local%20storage.%22)%3Breturn%3B%7Dconfirmed%20%3D%20confirm(%22Are%20you%20sure%20you%20want%20to%20delete%20this%20item%3F%20This%20CANNOT%20be%20easily%20undone!%22)%3Bif%20(confirmed%20%3D%3D%20true)%20%7Barray.splice(itemIndex%2C%201)%3Blet%20newItem%20%3D%20%7Belements%3A%20array%7D%3Barray%20%3D%20JSON.stringify(newItem)%3BlocalStorage.setItem(%22infinite-craft-data%22%2C%20array)%3Balert(%22Item%20deleted!%20Reloading!%22)%3Bwindow.location.reload()%3B%7Dconsole.log(%22DONE%22)%3B%7D)()%7D)()

**Comment by NerdyDragon777** [comment]
Sorry about that, I had used the wrong account to post this.

**Comment by CloudWaddie** [comment]
@NerdyDragon777 can you please make a pull request for this? I'm really busy coding something big!
