### ISSUE TITLE
Request to use code.

### ISSUE THREAD

**Issue by NerdyDragon777** [CloudWaddie/infinite-craft-hack#2]
I am developing a more advanced tool based around the script that you discovered. 
I would like to publish it myself for resume reasons (of course, crediting you for the base). 
If you decline, however, I will provide the code for you to publish, given that you credit me.
The code will be a collection of tools for Infinite Craft with a structural menu, but will be fully contained in a bookmarklet.

**Comment by CloudWaddie** [comment]
Sure! Do whatever you want with it, just remember to credit me! Good luck!

**Comment by CloudWaddie** [comment]
Sorry for my late response.

**Comment by CloudWaddie** [comment]
Also, I am happy to help if you need, although I know you might not want help as it is for your resume so don't stress about it.

**Comment by NerdyDragon777** [comment]
Oh, yes, I had forgotten about this. Thank you for your permission, I may work on it a bit more before posting it, but I most certainly will be crediting you for the original interface code.

**Comment by NerdyDragon777** [comment]
Oh, my, I accidentally posted that and closed the issue. Interesting that GitHub does not have a “confirm” option after clicking “Close with comment.”

**Comment by CloudWaddie** [comment]
Thanks!
